name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: [12.x, 14.x, 16.x]
      - uses: actions/cache@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build
        run: |
          npm install
          npm run-script deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/pec5
